### PR TITLE
use black for formatting

### PR DESCRIPTION
**Pull request by BenDoan**
https://github.com/ambv/black

### CODE REVIEW

**Comment by spacetag** [comment]
The heart is in the right place; maybe some of the settings can be tweaked?

**Comment by BenDoan** [comment]
Here's my argument for using black. Black's blurb about its goals:
> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
> 
> Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.

It's extremely powerful and convenient to be able to completely stop worrying about formatting on a project. You just have black run on save (or on commit, etc.), and your formatting is always consistent and correct. If you write some code that's not formatted properly, you hit save and it instantly pops into the correct state. 

I think the formatting looks fine, but IMO, having formatting that looks a little weird is completely worth it in exchange for never having to worry about formatting.

It's not really possible to tweak a few rules; the point of black is that you "cede control over minutiae of hand-formatting". You're trading being able to be picky about formatting for not having to worry about formatting.

@spacetag Does that change you opinion towards this change (in either direction)?

**Comment by spacetag** [comment]
I think it's a good idea to use it, even though I may not the look resulting from certain decisions it makes. For example, putting closing brackets on a new line and dedenting may not look very nice to me, but I understand it makes diffs look better (It's unfortunate we don't have smarter diff tools)

**Comment by pgayee694** [comment]
Would it be worth seeing how other auto-formatters do and deciding between which ones we prefer based on that?

**Pull request merged**
