### PR TITLE
remove null characters from output

### PR DESCRIPTION
**Pull request by BenDoan**

### CODE REVIEW

**Comment by BenDoan** [comment]
@spacetag I'm fine with just removing null characters; I don't think it's worth the effort to move to a different data type.

@pgayee694 I think null characters are the only thing likely to cause issues.

**Comment by benkonz** [comment]
This is an interesting problem. I am by no means an expert in character encoding, but shouldn't it be impossible to type a null unicode character?

**Comment by spacetag** [comment]
@benkonz Actually, there is a null unicode character (codepoint U+0000), and it is encodable in UTF-8: https://stackoverflow.com/questions/6907297/can-utf-8-contain-zero-byte

**Comment by benkonz** [comment]
The part I don't understand is how someone would, unintentionally, send a sequence of 8 zeros through using the site normally.

**Comment by BenDoan** [comment]
@benkonz This problem was caused by someone's _program_ outputting null characters. It's easy to reproduce with something like this:
```python
print('\0')
```

In their case, I believe they were creating a char array (which would be initialized to zero), and printing it out. Something like:
```java
char[] test  = new char[3];
System.out.println(test[0]);
```

**Pull request merged**
